name: Build Linux

on:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Deb
        run: |
          cd EltonKola_Web
          chmod +x gradlew  
          ./gradlew :composeApp:packageDeb

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: app.deb
          path: EltonKola_Web/composeApp/build/compose/binaries/main/deb/eltonkola_1.0.0-1_amd64.deb