name: Build All Binaries

on:
  workflow_dispatch:
jobs:
  debug-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build APK
        run: |
          cd eltonkola
          ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: eltonkola/androidApp/build/outputs/apk/debug/androidApp-debug.apk

