name: Build Windows

on:
  workflow_call:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Msi
        run: |
          cd EltonKola_Web
          chmod +x gradlew  
          ./gradlew :composeApp:packageMsi

      - name: Upload Msi
        uses: actions/upload-artifact@v4
        with:
          name: app.msi
          path: EltonKola_Web\desktopApp\build\compose\binaries\main\msi\com.eltonkola-1.0.0.msi