name: Build All Binaries

on:
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build APK
        run: |
          cd eltonkola
          ./gradlew androidApp:assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app.apk
          path: eltonkola/androidApp/build/outputs/apk/debug/androidApp-debug.apk

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Deb
        run: |
          cd eltonkola
          ./gradlew desktopApp:packageDeb
        
      - name: Upload DEB
        uses: actions/upload-artifact@v1
        with:
          name: app.deb
          path: eltonkola/desktopApp/build/compose/binaries/main/deb/EltonKola-1.0.0.deb

  build-web:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Deb
        run: |
          cd eltonkola
          ./gradlew jsApp:jsBrowserDistribution
          zip -r web.zip jsApp/build/distributions
        
      - name: Upload Web
        uses: actions/upload-artifact@v1
        with:
          name: web.zip
          path: eltonkola/web.zip

  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Deb
        run: |
          cd eltonkola
          ./gradlew desktopApp:packageDmg
                  
      - name: Upload Dmg
        uses: actions/upload-artifact@v1
        with:
          name: app.dmg
          path: eltonkola/desktopApp/build/compose/binaries/main/dmg/EltonKola-1.0.0.dmg

