name: Build macOS

on:
  workflow_call:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Dmg
        run: |
          cd EltonKola_Web
          chmod +x gradlew  
          ./gradlew :composeApp:packageDmg

      - name: Upload Dmg
        uses: actions/upload-artifact@v4
        with:
          name: app.dmg
          path: EltonKola_Web/desktopApp/build/compose/binaries/main/dmg/*.dmg
          if-no-files-found: error