name: Update Website

on:
  workflow_call:

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Prepare public directory structure
        run: |
          #rm -rf public
          rm -f public/downloads/*.apk
          rm -f public/downloads/*.deb
          rm -f public/downloads/*.msi
          rm -f public/downloads/*.dmg
          rm -f public/downloads/*.zip
          mkdir -p public/downloads

      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: web.zip
          path: public/downloads

      # - name: Download APK Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app.apk
      #     path: public/downloads
      # - name: Rename downloaded APK
      #   run: |
      #     mv public/downloads/*.apk public/downloads/app.apk
      #   shell: bash 

      # - name: Download DEB Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app.deb
      #     path: public/downloads
      # - name: Rename downloaded Deb
      #   run: |
      #     mv public/downloads/*.deb public/downloads/app.deb
      #   shell: bash 

        
      # - name: Download MSI Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app.msi
      #     path: public/downloads
      # - name: Rename downloaded Msi
      #   run: |
      #     mv public/downloads/*.msi public/downloads/app.msi
      #   shell: bash 

      # - name: Download DMG Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app.dmg
      #     path: public/downloads
      # - name: Rename downloaded Dmg
      #   run: |
      #     mv public/downloads/*.dmg public/downloads/app.dmg
      #   shell: bash 


      - name: Extract web content and organize files
        run: |
          echo "Contents of public/downloads before unzip:"
          ls -R public/downloads
          unzip -o public/downloads/web.zip -d public/
          echo "Contents of public/ after unzip:"
          ls -R public/

      - name: Create Pull Request for Website Update
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'update website content and binaries'
          branch: website_update
          delete-branch: true
          title: '[publish] Update website and app binaries'
          assignees: ${{ github.actor }}
          base: master
          body: |
            Update website content and application binaries.
            - Deployed new web build to `public/`
            - Copied all built binaries to `public/downloads/`
          labels: |
            deployment
            automated-pr